# Generated by Django 4.2.5 on 2023-10-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutpassForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outpass_date', models.DateField()),
                ('outpass_time', models.TimeField()),
                ('outpass_reason', models.CharField(choices=[('on-duty', 'On-Duty'), ('personal', 'Personal')], max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('return_to_company', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('return_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
